'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "Funzionalità di salvataggio automatico My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property BookChapterBold() As Boolean
        Get
            Return CType(Me("BookChapterBold"),Boolean)
        End Get
        Set
            Me("BookChapterBold") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property BookChapterItalic() As Boolean
        Get
            Return CType(Me("BookChapterItalic"),Boolean)
        End Get
        Set
            Me("BookChapterItalic") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property BookChapterUnderline() As Boolean
        Get
            Return CType(Me("BookChapterUnderline"),Boolean)
        End Get
        Set
            Me("BookChapterUnderline") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0, 0, 64")>  _
    Public Property BookChapterForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("BookChapterForeColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("BookChapterForeColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
    Public Property BookChapterBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("BookChapterBackColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("BookChapterBackColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 12pt")>  _
    Public Property BookChapterFont() As Global.System.Drawing.Font
        Get
            Return CType(Me("BookChapterFont"),Global.System.Drawing.Font)
        End Get
        Set
            Me("BookChapterFont") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TOP")>  _
    Public Property BookChapterPosition() As Global.BibleGetIO.POS
        Get
            Return CType(Me("BookChapterPosition"),Global.BibleGetIO.POS)
        End Get
        Set
            Me("BookChapterPosition") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 8.25pt")>  _
    Public Property VerseNumberFont() As Global.System.Drawing.Font
        Get
            Return CType(Me("VerseNumberFont"),Global.System.Drawing.Font)
        End Get
        Set
            Me("VerseNumberFont") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseNumberBold() As Boolean
        Get
            Return CType(Me("VerseNumberBold"),Boolean)
        End Get
        Set
            Me("VerseNumberBold") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseNumberItalic() As Boolean
        Get
            Return CType(Me("VerseNumberItalic"),Boolean)
        End Get
        Set
            Me("VerseNumberItalic") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseNumberUnderline() As Boolean
        Get
            Return CType(Me("VerseNumberUnderline"),Boolean)
        End Get
        Set
            Me("VerseNumberUnderline") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseNumberStrikethrough() As Boolean
        Get
            Return CType(Me("VerseNumberStrikethrough"),Boolean)
        End Get
        Set
            Me("VerseNumberStrikethrough") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
    Public Property VerseNumberForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("VerseNumberForeColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("VerseNumberForeColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
    Public Property VerseNumberBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("VerseNumberBackColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("VerseNumberBackColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SUPERSCRIPT")>  _
    Public Property VerseNumberVAlign() As Global.BibleGetIO.VALIGN
        Get
            Return CType(Me("VerseNumberVAlign"),Global.BibleGetIO.VALIGN)
        End Get
        Set
            Me("VerseNumberVAlign") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseTextBold() As Boolean
        Get
            Return CType(Me("VerseTextBold"),Boolean)
        End Get
        Set
            Me("VerseTextBold") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseTextItalic() As Boolean
        Get
            Return CType(Me("VerseTextItalic"),Boolean)
        End Get
        Set
            Me("VerseTextItalic") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseTextUnderline() As Boolean
        Get
            Return CType(Me("VerseTextUnderline"),Boolean)
        End Get
        Set
            Me("VerseTextUnderline") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VerseTextStrikethrough() As Boolean
        Get
            Return CType(Me("VerseTextStrikethrough"),Boolean)
        End Get
        Set
            Me("VerseTextStrikethrough") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
    Public Property VerseTextForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("VerseTextForeColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("VerseTextForeColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
    Public Property VerseTextBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("VerseTextBackColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("VerseTextBackColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("JUSTIFY")>  _
    Public Property ParagraphAlignment() As Global.BibleGetIO.ALIGN
        Get
            Return CType(Me("ParagraphAlignment"),Global.BibleGetIO.ALIGN)
        End Get
        Set
            Me("ParagraphAlignment") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LeftIndent() As Single
        Get
            Return CType(Me("LeftIndent"),Single)
        End Get
        Set
            Me("LeftIndent") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1.5")>  _
    Public Property Linespacing() As Single
        Get
            Return CType(Me("Linespacing"),Single)
        End Get
        Set
            Me("Linespacing") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("CEI2008,NABRE")>  _
    Public Property PreferredVersions() As String
        Get
            Return CType(Me("PreferredVersions"),String)
        End Get
        Set
            Me("PreferredVersions") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property NOVERSIONFORMATTING() As Boolean
        Get
            Return CType(Me("NOVERSIONFORMATTING"),Boolean)
        End Get
        Set
            Me("NOVERSIONFORMATTING") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property UpdateCheck() As Date
        Get
            Return CType(Me("UpdateCheck"),Date)
        End Get
        Set
            Me("UpdateCheck") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property NewVersionExists() As Boolean
        Get
            Return CType(Me("NewVersionExists"),Boolean)
        End Get
        Set
            Me("NewVersionExists") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property NewVersion() As String
        Get
            Return CType(Me("NewVersion"),String)
        End Get
        Set
            Me("NewVersion") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DEBUG_MODE() As Boolean
        Get
            Return CType(Me("DEBUG_MODE"),Boolean)
        End Get
        Set
            Me("DEBUG_MODE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property RightIndent() As Single
        Get
            Return CType(Me("RightIndent"),Single)
        End Get
        Set
            Me("RightIndent") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 12pt")>  _
    Public Property BibleVersionFont() As Global.System.Drawing.Font
        Get
            Return CType(Me("BibleVersionFont"),Global.System.Drawing.Font)
        End Get
        Set
            Me("BibleVersionFont") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
    Public Property BibleVersionForeColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("BibleVersionForeColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("BibleVersionForeColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Transparent")>  _
    Public Property BibleVersionBackColor() As Global.System.Drawing.Color
        Get
            Return CType(Me("BibleVersionBackColor"),Global.System.Drawing.Color)
        End Get
        Set
            Me("BibleVersionBackColor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman, 9.75pt")>  _
    Public Property VerseTextFont() As Global.System.Drawing.Font
        Get
            Return CType(Me("VerseTextFont"),Global.System.Drawing.Font)
        End Get
        Set
            Me("VerseTextFont") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TOP")>  _
    Public Property BibleVersionPosition() As Global.BibleGetIO.POS
        Get
            Return CType(Me("BibleVersionPosition"),Global.BibleGetIO.POS)
        End Get
        Set
            Me("BibleVersionPosition") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LEFT")>  _
    Public Property BibleVersionAlign() As Global.BibleGetIO.ALIGN
        Get
            Return CType(Me("BibleVersionAlign"),Global.BibleGetIO.ALIGN)
        End Get
        Set
            Me("BibleVersionAlign") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("NONE")>  _
    Public Property BibleVersionWrap() As Global.BibleGetIO.WRAP
        Get
            Return CType(Me("BibleVersionWrap"),Global.BibleGetIO.WRAP)
        End Get
        Set
            Me("BibleVersionWrap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("NONE")>  _
    Public Property BookChapterWrap() As Global.BibleGetIO.WRAP
        Get
            Return CType(Me("BookChapterWrap"),Global.BibleGetIO.WRAP)
        End Get
        Set
            Me("BookChapterWrap") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("LEFT")>  _
    Public Property BookChapterAlign() As Global.BibleGetIO.ALIGN
        Get
            Return CType(Me("BookChapterAlign"),Global.BibleGetIO.ALIGN)
        End Get
        Set
            Me("BookChapterAlign") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SHOW")>  _
    Public Property BibleVersionVisibility() As Global.BibleGetIO.VISIBILITY
        Get
            Return CType(Me("BibleVersionVisibility"),Global.BibleGetIO.VISIBILITY)
        End Get
        Set
            Me("BibleVersionVisibility") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("SHOW")>  _
    Public Property VerseNumberVisibility() As Global.BibleGetIO.VISIBILITY
        Get
            Return CType(Me("VerseNumberVisibility"),Global.BibleGetIO.VISIBILITY)
        End Get
        Set
            Me("VerseNumberVisibility") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("BIBLELANG")>  _
    Public Property BookChapterFormat() As Global.BibleGetIO.FORMAT
        Get
            Return CType(Me("BookChapterFormat"),Global.BibleGetIO.FORMAT)
        End Get
        Set
            Me("BookChapterFormat") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("wdInches")>  _
    Public Property CurrentDisplayUnit() As Global.Microsoft.Office.Interop.Word.WdMeasurementUnits
        Get
            Return CType(Me("CurrentDisplayUnit"),Global.Microsoft.Office.Interop.Word.WdMeasurementUnits)
        End Get
        Set
            Me("CurrentDisplayUnit") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property BookChapterFullReference() As Boolean
        Get
            Return CType(Me("BookChapterFullReference"),Boolean)
        End Get
        Set
            Me("BookChapterFullReference") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("HEBREW")>  _
    Public Property PreferOrigin() As Global.BibleGetIO.PREFERORIGIN
        Get
            Return CType(Me("PreferOrigin"),Global.BibleGetIO.PREFERORIGIN)
        End Get
        Set
            Me("PreferOrigin") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.BibleGetIO.MySettings
            Get
                Return Global.BibleGetIO.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
