'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
'tramite uno strumento quale ResGen o Visual Studio.
'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
'con l'opzione /str oppure ricompilare il progetto VS.
'''<summary>
'''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class BibleGetResource
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BibleGetIO.BibleGetResource", GetType(BibleGetResource).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
    '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a &quot;,&quot;: the comma is the chapter-verse delimiter. &quot;Matthew 1,5&quot; means the book (gospel) of Matthew, chapter 1, verse 5. (In English notation: &quot;Matthew 1:5&quot;.).
    '''</summary>
    Friend Shared ReadOnly Property _____the_comma_is_the_chapter_verse_delimiter___Matthew_1_5__means_the_book__gospel__of_Matthew__chapter_1__verse_5___In_English_notation___Matthew_1_5___() As String
        Get
            Return ResourceManager.GetString(""","": the comma is the chapter-verse delimiter. ""Matthew 1,5"" means the book (gosp"& _ 
                    "el) of Matthew, chapter 1, verse 5. (In English notation: ""Matthew 1:5"".)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a &quot;-&quot;: the dash is a range delimiter, which can be used in a variety of ways:.
    '''</summary>
    Friend Shared ReadOnly Property _____the_dash_is_a_range_delimiter__which_can_be_used_in_a_variety_of_ways_() As String
        Get
            Return ResourceManager.GetString("""-"": the dash is a range delimiter, which can be used in a variety of ways:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a &quot;.&quot;: the dot is a delimiter between verses. &quot;Matthew 1,5.7&quot; means the book (gospel) of Matthew, chapter 1, verses 5 and 7. (In English notation: &quot;Matthew 1:5,7&quot;.).
    '''</summary>
    Friend Shared ReadOnly Property _____the_dot_is_a_delimiter_between_verses___Matthew_1_5_7__means_the_book__gospel__of_Matthew__chapter_1__verses_5_and_7___In_English_notation___Matthew_1_5_7___() As String
        Get
            Return ResourceManager.GetString("""."": the dot is a delimiter between verses. ""Matthew 1,5.7"" means the book (gospe"& _ 
                    "l) of Matthew, chapter 1, verses 5 and 7. (In English notation: ""Matthew 1:5,7""."& _ 
                    ")", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a (e.g. Mt 1,1-10.12-15;5,3-4;Jn 3,16).
    '''</summary>
    Friend Shared ReadOnly Property _e_g__Mt_1_1_10_12_15_5_3_4_Jn_3_16_() As String
        Get
            Return ResourceManager.GetString("(e.g. Mt 1,1-10.12-15;5,3-4;Jn 3,16)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Select.
    '''</summary>
    Friend Shared ReadOnly Property _Select() As String
        Get
            Return ResourceManager.GetString("Select", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A basic query consists of at least two elements: the bible book and the chapter..
    '''</summary>
    Friend Shared ReadOnly Property A_basic_query_consists_of_at_least_two_elements__the_bible_book_and_the_chapter_() As String
        Get
            Return ResourceManager.GetString("A basic query consists of at least two elements: the bible book and the chapter.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A chapter in the query is out of bounds: there is no chapter &lt;{0}&gt; in the book &lt;{1}&gt; in the requested version &lt;{2}&gt;, the last possible chapter is &lt;{3}&gt;.
    '''</summary>
    Friend Shared ReadOnly Property A_chapter_in_the_query_is_out_of_bounds__there_is_no_chapter___0___in_the_book___1___in_the_requested_version___2____the_last_possible_chapter_is___3__() As String
        Get
            Return ResourceManager.GetString("A chapter in the query is out of bounds: there is no chapter <{0}> in the book <{"& _ 
                    "1}> in the requested version <{2}>, the last possible chapter is <{3}>", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A comma must be preceded and followed by 1 to 3 digits of which the first digit cannot be zero..
    '''</summary>
    Friend Shared ReadOnly Property A_comma_must_be_preceded_and_followed_by_1_to_3_digits_of_which_the_first_digit_cannot_be_zero_() As String
        Get
            Return ResourceManager.GetString("A comma must be preceded and followed by 1 to 3 digits of which the first digit c"& _ 
                    "annot be zero.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A dash must be preceded and followed by 1 to 3 digits of which the first digit cannot be zero..
    '''</summary>
    Friend Shared ReadOnly Property A_dash_must_be_preceded_and_followed_by_1_to_3_digits_of_which_the_first_digit_cannot_be_zero_() As String
        Get
            Return ResourceManager.GetString("A dash must be preceded and followed by 1 to 3 digits of which the first digit ca"& _ 
                    "nnot be zero.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A dot must be preceded and followed by 1 to 3 digits of which the first digit cannot be zero..
    '''</summary>
    Friend Shared ReadOnly Property A_dot_must_be_preceded_and_followed_by_1_to_3_digits_of_which_the_first_digit_cannot_be_zero_() As String
        Get
            Return ResourceManager.GetString("A dot must be preceded and followed by 1 to 3 digits of which the first digit can"& _ 
                    "not be zero.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A query that doesn&apos;t start with a book indicator must however start with a valid chapter indicator!.
    '''</summary>
    Friend Shared ReadOnly Property A_query_that_doesn_t_start_with_a_book_indicator_must_however_start_with_a_valid_chapter_indicator_() As String
        Get
            Return ResourceManager.GetString("A query that doesn't start with a book indicator must however start with a valid "& _ 
                    "chapter indicator!", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a A verse in the query is out of bounds: there is no verse &lt;{0}&gt; in the book &lt;{1}&gt; at chapter &lt;{2}&gt; in the requested version &lt;{3}&gt;, the last possible verse is &lt;{4}&gt;.
    '''</summary>
    Friend Shared ReadOnly Property A_verse_in_the_query_is_out_of_bounds__there_is_no_verse___0___in_the_book___1___at_chapter___2___in_the_requested_version___3____the_last_possible_verse_is___4__() As String
        Get
            Return ResourceManager.GetString("A verse in the query is out of bounds: there is no verse <{0}> in the book <{1}> "& _ 
                    "at chapter <{2}> in the requested version <{3}>, the last possible verse is <{4}"& _ 
                    ">", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a ABBREVIATION.
    '''</summary>
    Friend Shared ReadOnly Property ABBREVIATION() As String
        Get
            Return ResourceManager.GetString("ABBREVIATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a About this plugin.
    '''</summary>
    Friend Shared ReadOnly Property About_this_plugin() As String
        Get
            Return ResourceManager.GetString("About this plugin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Action.
    '''</summary>
    Friend Shared ReadOnly Property Action() As String
        Get
            Return ResourceManager.GetString("Action", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a After the &apos;Help&apos; menu item that opens up this same help window, the last three menu items are:.
    '''</summary>
    Friend Shared ReadOnly Property After_the__Help__menu_item_that_opens_up_this_same_help_window__the_last_three_menu_items_are_() As String
        Get
            Return ResourceManager.GetString("After the 'Help' menu item that opens up this same help window, the last three me"& _ 
                    "nu items are:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Alignment.
    '''</summary>
    Friend Shared ReadOnly Property Alignment() As String
        Get
            Return ResourceManager.GetString("Alignment", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a AUTHOR.
    '''</summary>
    Friend Shared ReadOnly Property AUTHOR() As String
        Get
            Return ResourceManager.GetString("AUTHOR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Biblical Books and Abbreviations.
    '''</summary>
    Friend Shared ReadOnly Property Biblical_Books_and_Abbreviations() As String
        Get
            Return ResourceManager.GetString("Biblical Books and Abbreviations", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a BOOK.
    '''</summary>
    Friend Shared ReadOnly Property BOOK() As String
        Get
            Return ResourceManager.GetString("BOOK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Book / Chapter.
    '''</summary>
    Friend Shared ReadOnly Property Book___Chapter() As String
        Get
            Return ResourceManager.GetString("Book / Chapter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Cancel.
    '''</summary>
    Friend Shared ReadOnly Property Cancel() As String
        Get
            Return ResourceManager.GetString("Cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Chapters must be consecutive. Instead the first chapter indicator &lt;{0}&gt; is greater than or equal to the second chapter indicator &lt;{1}&gt; in the expression &lt;{2}&gt;.
    '''</summary>
    Friend Shared ReadOnly Property Chapters_must_be_consecutive__Instead_the_first_chapter_indicator___0___is_greater_than_or_equal_to_the_second_chapter_indicator___1___in_the_expression___2__() As String
        Get
            Return ResourceManager.GetString("Chapters must be consecutive. Instead the first chapter indicator <{0}> is greate"& _ 
                    "r than or equal to the second chapter indicator <{1}> in the expression <{2}>", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Choose version (or versions).
    '''</summary>
    Friend Shared ReadOnly Property Choose_version__or_versions_() As String
        Get
            Return ResourceManager.GetString("Choose version (or versions)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a COLLABORATORS.
    '''</summary>
    Friend Shared ReadOnly Property COLLABORATORS() As String
        Get
            Return ResourceManager.GetString("COLLABORATORS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Make a contribution.
    '''</summary>
    Friend Shared ReadOnly Property Contribute() As String
        Get
            Return ResourceManager.GetString("Contribute", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Current information from the BibleGet Server:.
    '''</summary>
    Friend Shared ReadOnly Property Current_information_from_the_BibleGet_Server_() As String
        Get
            Return ResourceManager.GetString("Current information from the BibleGet Server:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Description of the menu icons and their functionality..
    '''</summary>
    Friend Shared ReadOnly Property Description_of_the_menu_icons_and_their_functionality_() As String
        Get
            Return ResourceManager.GetString("Description of the menu icons and their functionality.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Different combinations of books, chapters, and verses can be formed using the comma delimiter and the dot delimiter (in european notation, in english notation instead a colon is used instead of a comma and a comma is used instead of a dot):.
    '''</summary>
    Friend Shared ReadOnly Property Different_combinations_of_books__chapters__and_verses_can_be_formed_using_the_comma_delimiter_and_the_dot_delimiter__in_european_notation__in_english_notation_instead_a_colon_is_used_instead_of_a_comma_and_a_comma_is_used_instead_of_a_dot__() As String
        Get
            Return ResourceManager.GetString("Different combinations of books, chapters, and verses can be formed using the com"& _ 
                    "ma delimiter and the dot delimiter (in european notation, in english notation in"& _ 
                    "stead a colon is used instead of a comma and a comma is used instead of a dot):", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Different combinations of these delimiters can form fairly complex queries, for example &quot;Mt1,1-3.5.7-9&quot; means the gospel according to Matthew, chapter 1, verses 1 to 3, verse 5, and verses 7 to 9. (In English notation: &quot;Mt1:1-3,5,7-9&quot;.).
    '''</summary>
    Friend Shared ReadOnly Property Different_combinations_of_these_delimiters_can_form_fairly_complex_queries__for_example__Mt1_1_3_5_7_9__means_the_gospel_according_to_Matthew__chapter_1__verses_1_to_3__verse_5__and_verses_7_to_9___In_English_notation___Mt1_1_3_5_7_9___() As String
        Get
            Return ResourceManager.GetString("Different combinations of these delimiters can form fairly complex queries, for e"& _ 
                    "xample ""Mt1,1-3.5.7-9"" means the gospel according to Matthew, chapter 1, verses "& _ 
                    "1 to 3, verse 5, and verses 7 to 9. (In English notation: ""Mt1:1-3,5,7-9"".)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a e.g. creation.
    '''</summary>
    Friend Shared ReadOnly Property e_g__creation() As String
        Get
            Return ResourceManager.GetString("e.g. creation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a EMAIL ADDRESS FOR INFORMATION OR FEEDBACK ON THE PROJECT.
    '''</summary>
    Friend Shared ReadOnly Property EMAIL_ADDRESS_FOR_INFORMATION_OR_FEEDBACK_ON_THE_PROJECT() As String
        Get
            Return ResourceManager.GetString("EMAIL ADDRESS FOR INFORMATION OR FEEDBACK ON THE PROJECT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a For a range of chapters: &quot;Matthew 1-2&quot; means the gospel according to Matthew, from chapter 1 to chapter 2..
    '''</summary>
    Friend Shared ReadOnly Property For_a_range_of_chapters___Matthew_1_2__means_the_gospel_according_to_Matthew__from_chapter_1_to_chapter_2_() As String
        Get
            Return ResourceManager.GetString("For a range of chapters: ""Matthew 1-2"" means the gospel according to Matthew, fro"& _ 
                    "m chapter 1 to chapter 2.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a For a range of verses that span over different chapters: &quot;Matthew 1,5-2,13&quot; means the gospel according to Matthew, from chapter 1, verse 5 to chapter 2, verse 13. (In English notation: &quot;Matthew 1:5-2:13&quot;.).
    '''</summary>
    Friend Shared ReadOnly Property For_a_range_of_verses_that_span_over_different_chapters___Matthew_1_5_2_13__means_the_gospel_according_to_Matthew__from_chapter_1__verse_5_to_chapter_2__verse_13___In_English_notation___Matthew_1_5_2_13___() As String
        Get
            Return ResourceManager.GetString("For a range of verses that span over different chapters: ""Matthew 1,5-2,13"" means"& _ 
                    " the gospel according to Matthew, from chapter 1, verse 5 to chapter 2, verse 13"& _ 
                    ". (In English notation: ""Matthew 1:5-2:13"".)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a For a range of verses within the same chapter: &quot;Matthew 1,1-5&quot; means the gospel according to Matthew, chapter 1, from verse 1 to verse 5. (In English notation: &quot;Matthew 1:1-5&quot;.).
    '''</summary>
    Friend Shared ReadOnly Property For_a_range_of_verses_within_the_same_chapter___Matthew_1_1_5__means_the_gospel_according_to_Matthew__chapter_1__from_verse_1_to_verse_5___In_English_notation___Matthew_1_1_5___() As String
        Get
            Return ResourceManager.GetString("For a range of verses within the same chapter: ""Matthew 1,1-5"" means the gospel a"& _ 
                    "ccording to Matthew, chapter 1, from verse 1 to verse 5. (In English notation: """& _ 
                    "Matthew 1:1-5"".)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a For example, &quot;Matthew 1,1;2,13&quot; means the gospel according to Matthew, chapter 1 verse 1 and chapter 2 verse 13. (In English notation: &quot;Matthew 1:1;2:13&quot;.).
    '''</summary>
    Friend Shared ReadOnly Property For_example___Matthew_1_1_2_13__means_the_gospel_according_to_Matthew__chapter_1_verse_1_and_chapter_2_verse_13___In_English_notation___Matthew_1_1_2_13___() As String
        Get
            Return ResourceManager.GetString("For example, ""Matthew 1,1;2,13"" means the gospel according to Matthew, chapter 1 "& _ 
                    "verse 1 and chapter 2 verse 13. (In English notation: ""Matthew 1:1;2:13"".)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a For example, the query &quot;Matthew 1&quot; means the book of Matthew (or better the gospel according to Matthew) at chapter 1..
    '''</summary>
    Friend Shared ReadOnly Property For_example__the_query__Matthew_1__means_the_book_of_Matthew__or_better_the_gospel_according_to_Matthew__at_chapter_1_() As String
        Get
            Return ResourceManager.GetString("For example, the query ""Matthew 1"" means the book of Matthew (or better the gospe"& _ 
                    "l according to Matthew) at chapter 1.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Formatting preferences can be set using the &apos;Preferences&apos; window. You can choose the desired font for the Bible quotes as well as the desired line-spacing, and you can choose separate formatting (font size, font color, font style) for the book / chapter, for the verse numbers, and for the verse text. Preferences are saved automatically..
    '''</summary>
    Friend Shared ReadOnly Property Formatting_preferences_can_be_set_using_the__Preferences__window__You_can_choose_the_desired_font_for_the_Bible_quotes_as_well_as_the_desired_line_spacing__and_you_can_choose_separate_formatting__font_size__font_color__font_style__for_the_book___chapter__for_the_verse_numbers__and_for_the_verse_text__Preferences_are_saved_automatically_() As String
        Get
            Return ResourceManager.GetString("Formatting preferences can be set using the 'Preferences' window. You can choose "& _ 
                    "the desired font for the Bible quotes as well as the desired line-spacing, and y"& _ 
                    "ou can choose separate formatting (font size, font color, font style) for the bo"& _ 
                    "ok / chapter, for the verse numbers, and for the verse text. Preferences are sav"& _ 
                    "ed automatically.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Formulation of the Queries.
    '''</summary>
    Friend Shared ReadOnly Property Formulation_of_the_Queries() As String
        Get
            Return ResourceManager.GetString("Formulation of the Queries", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Giovanni Gregori (computing) and Simone Urbinati (MUG Roma Tre).
    '''</summary>
    Friend Shared ReadOnly Property Giovanni_Gregori__computing__and_Simone_Urbinati__MUG_Roma_Tre_() As String
        Get
            Return ResourceManager.GetString("Giovanni Gregori (computing) and Simone Urbinati (MUG Roma Tre)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Help.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Help for BibleGet (Microsoft Word 2007+).
    '''</summary>
    Friend Shared ReadOnly Property Help_for_BibleGet__Microsoft_Office_() As String
        Get
            Return ResourceManager.GetString("Help for BibleGet (Microsoft Office)", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Here is a list of valid books and their corresponding abbreviations, either of which can be used in the querystrings..
    '''</summary>
    Friend Shared ReadOnly Property Here_is_a_list_of_valid_books_and_their_corresponding_abbreviations__either_of_which_can_be_used_in_the_querystrings_() As String
        Get
            Return ResourceManager.GetString("Here is a list of valid books and their corresponding abbreviations, either of wh"& _ 
                    "ich can be used in the querystrings.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Here is an example of multiple complex queries combined into a single querystring: &quot;Genesis 1,3-5.7.9-11.13;2,4-9.11-13;Apocalypse 3,10.12-14&quot;. (In English notation: &quot;Genesis 1:3-5,7,9-11,13;2:4-9,11-13;Apocalypse 3:10,12-14&quot;)..
    '''</summary>
    Friend Shared ReadOnly Property Here_is_an_example_of_multiple_complex_queries_combined_into_a_single_querystring___Genesis_1_3_5_7_9_11_13_2_4_9_11_13_Apocalypse_3_10_12_14____In_English_notation___Genesis_1_3_5_7_9_11_13_2_4_9_11_13_Apocalypse_3_10_12_14___() As String
        Get
            Return ResourceManager.GetString("Here is an example of multiple complex queries combined into a single querystring"& _ 
                    ": ""Genesis 1,3-5.7.9-11.13;2,4-9.11-13;Apocalypse 3,10.12-14"". (In English notat"& _ 
                    "ion: ""Genesis 1:3-5,7,9-11,13;2:4-9,11-13;Apocalypse 3:10,12-14"").", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a How to formulate a bible query.
    '''</summary>
    Friend Shared ReadOnly Property How_to_formulate_a_bible_query() As String
        Get
            Return ResourceManager.GetString("How to formulate a bible query", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a How to use the plugin.
    '''</summary>
    Friend Shared ReadOnly Property How_to_use_the_plugin() As String
        Get
            Return ResourceManager.GetString("How to use the plugin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a If the query following the semi-colon refers to the same book as the preceding query, it is not necessary to indicate the book a second time..
    '''</summary>
    Friend Shared ReadOnly Property If_the_query_following_the_semi_colon_refers_to_the_same_book_as_the_preceding_query__it_is_not_necessary_to_indicate_the_book_a_second_time_() As String
        Get
            Return ResourceManager.GetString("If the query following the semi-colon refers to the same book as the preceding qu"& _ 
                    "ery, it is not necessary to indicate the book a second time.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a If there is a chapter-verse construct following a dash, there must also be a chapter-verse construct preceding the same dash..
    '''</summary>
    Friend Shared ReadOnly Property If_there_is_a_chapter_verse_construct_following_a_dash__there_must_also_be_a_chapter_verse_construct_preceding_the_same_dash_() As String
        Get
            Return ResourceManager.GetString("If there is a chapter-verse construct following a dash, there must also be a chap"& _ 
                    "ter-verse construct preceding the same dash.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a If you click on the menu item &apos;&apos;{0}&apos;&apos;, an input window will open where you can input your query and choose the version or versions you would like to take the quote from..
    '''</summary>
    Friend Shared ReadOnly Property If_you_click_on_the_menu_item____0_____an_input_window_will_open_where_you_can_input_your_query_and_choose_the_version_or_versions_you_would_like_to_take_the_quote_from_() As String
        Get
            Return ResourceManager.GetString("If you click on the menu item ''{0}'', an input window will open where you can in"& _ 
                    "put your query and choose the version or versions you would like to take the quo"& _ 
                    "te from.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a In order to renew the information from the BibleGet server, click on the &apos;&apos;{0}&apos;&apos; menu item, and then click on the button &apos;&apos;{1}&apos;&apos;..
    '''</summary>
    Friend Shared ReadOnly Property In_order_to_renew_the_information_from_the_BibleGet_server__click_on_the____0____menu_item__and_then_click_on_the_button____1____() As String
        Get
            Return ResourceManager.GetString("In order to renew the information from the BibleGet server, click on the ''{0}'' "& _ 
                    "menu item, and then click on the button ''{1}''.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Information on the BibleGet I/O Project.
    '''</summary>
    Friend Shared ReadOnly Property Information_on_the_BibleGet_I_O_Project() As String
        Get
            Return ResourceManager.GetString("Information on the BibleGet I/O Project", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Insert quote from input window.
    '''</summary>
    Friend Shared ReadOnly Property Insert_quote_from_input_window() As String
        Get
            Return ResourceManager.GetString("Insert quote from input window", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Insert quote from text selection.
    '''</summary>
    Friend Shared ReadOnly Property Insert_quote_from_text_selection() As String
        Get
            Return ResourceManager.GetString("Insert quote from text selection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Instructions.
    '''</summary>
    Friend Shared ReadOnly Property Instructions() As String
        Get
            Return ResourceManager.GetString("Instructions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a It doesn&apos;t matter whether or not you use a space between the book and the chapter, the querystring will be interpreted just the same..
    '''</summary>
    Friend Shared ReadOnly Property It_doesn_t_matter_whether_or_not_you_use_a_space_between_the_book_and_the_chapter__the_querystring_will_be_interpreted_just_the_same_() As String
        Get
            Return ResourceManager.GetString("It doesn't matter whether or not you use a space between the book and the chapter"& _ 
                    ", the querystring will be interpreted just the same.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a It is a part of the &lt;b&gt;BibleGet Project&lt;/b&gt; at {0}..
    '''</summary>
    Friend Shared ReadOnly Property It_is_a_part_of_the__b_BibleGet_Project__b__at__0__() As String
        Get
            Return ResourceManager.GetString("It is a part of the <b>BibleGet Project</b> at {0}.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a It is also indifferent whether you use uppercase or lowercase letters, the querystring will be interpreted just the same..
    '''</summary>
    Friend Shared ReadOnly Property It_is_also_indifferent_whether_you_use_uppercase_or_lowercase_letters__the_querystring_will_be_interpreted_just_the_same_() As String
        Get
            Return ResourceManager.GetString("It is also indifferent whether you use uppercase or lowercase letters, the querys"& _ 
                    "tring will be interpreted just the same.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Left Indent.
    '''</summary>
    Friend Shared ReadOnly Property Left_Indent() As String
        Get
            Return ResourceManager.GetString("Left Indent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Line-spacing.
    '''</summary>
    Friend Shared ReadOnly Property Line_spacing() As String
        Get
            Return ResourceManager.GetString("Line-spacing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Mixed notations have been detected. Please use either english notation or european notation..
    '''</summary>
    Friend Shared ReadOnly Property Mixed_notations_have_been_detected__Please_use_either_english_notation_or_european_notation_() As String
        Get
            Return ResourceManager.GetString("Mixed notations have been detected. Please use either english notation or europea"& _ 
                    "n notation.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Multiple queries can be combined together using a semi-colon &quot;;&quot;..
    '''</summary>
    Friend Shared ReadOnly Property Multiple_queries_can_be_combined_together_using_a_semi_colon_____() As String
        Get
            Return ResourceManager.GetString("Multiple queries can be combined together using a semi-colon "";"".", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Once the extension is installed, a new menu &apos;BibleGet I/O&apos; will appear on the menu bar. Also a new floating toolbar will appear. The buttons on the floating toolbar correspond to the menu items in the new menu, as can be seen in this image:.
    '''</summary>
    Friend Shared ReadOnly Property Once_the_extension_is_installed__a_new_menu__BibleGet_I_O__will_appear_on_the_menu_bar__Also_a_new_floating_toolbar_will_appear__The_buttons_on_the_floating_toolbar_correspond_to_the_menu_items_in_the_new_menu__as_can_be_seen_in_this_image_() As String
        Get
            Return ResourceManager.GetString("Once the extension is installed, a new menu 'BibleGet I/O' will appear on the men"& _ 
                    "u bar. Also a new floating toolbar will appear. The buttons on the floating tool"& _ 
                    "bar correspond to the menu items in the new menu, as can be seen in this image:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Override Bible Version Formatting.
    '''</summary>
    Friend Shared ReadOnly Property Override_Bible_Version_Formatting() As String
        Get
            Return ResourceManager.GetString("Override Bible Version Formatting", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Paragraph.
    '''</summary>
    Friend Shared ReadOnly Property Paragraph() As String
        Get
            Return ResourceManager.GetString("Paragraph", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Preview.
    '''</summary>
    Friend Shared ReadOnly Property Preview() As String
        Get
            Return ResourceManager.GetString("Preview", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a PROJECT WEBSITE.
    '''</summary>
    Friend Shared ReadOnly Property PROJECT_WEBSITE() As String
        Get
            Return ResourceManager.GetString("PROJECT WEBSITE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a RENEW SERVER DATA.
    '''</summary>
    Friend Shared ReadOnly Property RENEW_SERVER_DATA() As String
        Get
            Return ResourceManager.GetString("RENEW SERVER DATA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Right Indent.
    '''</summary>
    Friend Shared ReadOnly Property Right_Indent() As String
        Get
            Return ResourceManager.GetString("Right Indent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Search.
    '''</summary>
    Friend Shared ReadOnly Property Search() As String
        Get
            Return ResourceManager.GetString("Search", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a See the list of valid books and abbreviations in the section {0}..
    '''</summary>
    Friend Shared ReadOnly Property See_the_list_of_valid_books_and_abbreviations_in_the_section__0__() As String
        Get
            Return ResourceManager.GetString("See the list of valid books and abbreviations in the section {0}.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Send feedback.
    '''</summary>
    Friend Shared ReadOnly Property Send_feedback() As String
        Get
            Return ResourceManager.GetString("Send feedback", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Send query.
    '''</summary>
    Friend Shared ReadOnly Property Send_query() As String
        Get
            Return ResourceManager.GetString("Send query", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Sends the request to the server and returns the results to the document..
    '''</summary>
    Friend Shared ReadOnly Property Sends_the_request_to_the_server_and_returns_the_results_to_the_document_() As String
        Get
            Return ResourceManager.GetString("Sends the request to the server and returns the results to the document.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Some Bible versions have their own formatting. 
    '''This is left by default to keep the text as close as possible to the original.
    '''If however you need to have consistent formatting in your document, 
    '''you may override the Bible version&apos;s own formatting..
    '''</summary>
    Friend Shared ReadOnly Property Some_Bible_versions_have_their_own_formatting__This_is_left_by_default_to_keep_the_text_as_close_as_possible_to_the_original__br__If_however_you_need_to_have_consistent_formatting_in_your_document__you_may_override_the_Bible_version_s_own_formatting_() As String
        Get
            Return ResourceManager.GetString("Some Bible versions have their own formatting. This is left by default to keep th"& _ 
                    "e text as close as possible to the original.<br> If however you need to have con"& _ 
                    "sistent formatting in your document, you may override the Bible version's own fo"& _ 
                    "rmatting.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The &lt;b&gt;BibleGet Project&lt;/b&gt; is an independent project born from the personal initiative of John R. D&apos;Orazio, and is not funded by any kind of corporation..
    '''</summary>
    Friend Shared ReadOnly Property The__b_BibleGet_Project__b__is_an_independent_project_born_from_the_personal_initiative_of_John_R__D_Orazio__and_is_not_funded_by_any_kind_of_corporation_() As String
        Get
            Return ResourceManager.GetString("The <b>BibleGet Project</b> is an independent project born from the personal init"& _ 
                    "iative of John R. D'Orazio, and is not funded by any kind of corporation.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The abbreviations do not always correspond with those proposed by the various editions of the Bible, because they would conflict with those proposed by other editions..
    '''</summary>
    Friend Shared ReadOnly Property The_abbreviations_do_not_always_correspond_with_those_proposed_by_the_various_editions_of_the_Bible__because_they_would_conflict_with_those_proposed_by_other_editions_() As String
        Get
            Return ResourceManager.GetString("The abbreviations do not always correspond with those proposed by the various edi"& _ 
                    "tions of the Bible, because they would conflict with those proposed by other edi"& _ 
                    "tions.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The author would like to thank &lt;b&gt;Giovanni Gregori&lt;/b&gt; and &lt;b&gt;Simone Urbinati&lt;/b&gt; for their code contributions..
    '''</summary>
    Friend Shared ReadOnly Property The_author_would_like_to_thank__b_Giovanni_Gregori__b__and__b_Simone_Urbinati__b__for_their_code_contributions_() As String
        Get
            Return ResourceManager.GetString("The author would like to thank <b>Giovanni Gregori</b> and <b>Simone Urbinati</b>"& _ 
                    " for their code contributions.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The bible book can be written out in full, or in an abbreviated form..
    '''</summary>
    Friend Shared ReadOnly Property The_bible_book_can_be_written_out_in_full__or_in_an_abbreviated_form_() As String
        Get
            Return ResourceManager.GetString("The bible book can be written out in full, or in an abbreviated form.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The BibleGet database currently supports {0} versions of the Bible in {1} different languages:.
    '''</summary>
    Friend Shared ReadOnly Property The_BibleGet_database_currently_supports__0__versions_of_the_Bible_in__1__different_languages_() As String
        Get
            Return ResourceManager.GetString("The BibleGet database currently supports {0} versions of the Bible in {1} differe"& _ 
                    "nt languages:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The BibleGet engine currently understands the names of the books of the Bible in {0} different languages:.
    '''</summary>
    Friend Shared ReadOnly Property The_BibleGet_engine_currently_understands_the_names_of_the_books_of_the_Bible_in__0__different_languages_() As String
        Get
            Return ResourceManager.GetString("The BibleGet engine currently understands the names of the books of the Bible in "& _ 
                    "{0} different languages:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The BibleGet engine recognizes the names of the books of the bible in {0} different languages: {1}.
    '''</summary>
    Friend Shared ReadOnly Property The_BibleGet_engine_recognizes_the_names_of_the_books_of_the_bible_in__0__different_languages___1_() As String
        Get
            Return ResourceManager.GetString("The BibleGet engine recognizes the names of the books of the bible in {0} differe"& _ 
                    "nt languages: {1}", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The book indicator &lt;{0}&gt; in the query &lt;{1}&gt; is not valid. Please check the documentation for a list of valid book indicators..
    '''</summary>
    Friend Shared ReadOnly Property The_book_indicator___0___in_the_query___1___is_not_valid__Please_check_the_documentation_for_a_list_of_valid_book_indicators_() As String
        Get
            Return ResourceManager.GetString("The book indicator <{0}> in the query <{1}> is not valid. Please check the docume"& _ 
                    "ntation for a list of valid book indicators.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The first query &lt;{0}&gt; in the querystring &lt;{1}&gt; must start with a valid book indicator!.
    '''</summary>
    Friend Shared ReadOnly Property The_first_query___0___in_the_querystring___1___must_start_with_a_valid_book_indicator_() As String
        Get
            Return ResourceManager.GetString("The first query <{0}> in the querystring <{1}> must start with a valid book indic"& _ 
                    "ator!", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The first way is by using the input window..
    '''</summary>
    Friend Shared ReadOnly Property The_first_way_is_by_using_the_input_window_() As String
        Get
            Return ResourceManager.GetString("The first way is by using the input window.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The Help is divided into three sections:.
    '''</summary>
    Friend Shared ReadOnly Property The_Help_is_divided_into_three_sections_() As String
        Get
            Return ResourceManager.GetString("The Help is divided into three sections:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The queries for bible quotes must be formulated using standard notation for bible citation..
    '''</summary>
    Friend Shared ReadOnly Property The_queries_for_bible_quotes_must_be_formulated_using_standard_notation_for_bible_citation_() As String
        Get
            Return ResourceManager.GetString("The queries for bible quotes must be formulated using standard notation for bible"& _ 
                    " citation.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The second way is by writing your desired quote directly in the document, and then selecting it and choosing the menu item &apos;&apos;{0}&apos;&apos;. The selected text will be substituted by the Bible Quote retrieved from the BibleGet server..
    '''</summary>
    Friend Shared ReadOnly Property The_second_way_is_by_writing_your_desired_quote_directly_in_the_document__and_then_selecting_it_and_choosing_the_menu_item____0_____The_selected_text_will_be_substituted_by_the_Bible_Quote_retrieved_from_the_BibleGet_server_() As String
        Get
            Return ResourceManager.GetString("The second way is by writing your desired quote directly in the document, and the"& _ 
                    "n selecting it and choosing the menu item ''{0}''. The selected text will be sub"& _ 
                    "stituted by the Bible Quote retrieved from the BibleGet server.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a The versions previously selected in the &apos;&apos;{0}&apos;&apos; window will be used, so you must have selected your preferred versions at least once from the &apos;&apos;{0}&apos;&apos; window..
    '''</summary>
    Friend Shared ReadOnly Property The_versions_previously_selected_in_the____0____window_will_be_used__so_you_must_have_selected_your_preferred_versions_at_least_once_from_the____0____window_() As String
        Get
            Return ResourceManager.GetString("The versions previously selected in the ''{0}'' window will be used, so you must "& _ 
                    "have selected your preferred versions at least once from the ''{0}'' window.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a There are multiple dashes in the query, but there are not enough dots. There can only be one more dash than dots..
    '''</summary>
    Friend Shared ReadOnly Property There_are_multiple_dashes_in_the_query__but_there_are_not_enough_dots__There_can_only_be_one_more_dash_than_dots_() As String
        Get
            Return ResourceManager.GetString("There are multiple dashes in the query, but there are not enough dots. There can "& _ 
                    "only be one more dash than dots.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a There are two ways of inserting a bible quote into a document..
    '''</summary>
    Friend Shared ReadOnly Property There_are_two_ways_of_inserting_a_bible_quote_into_a_document_() As String
        Get
            Return ResourceManager.GetString("There are two ways of inserting a bible quote into a document.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a There was a problem communicating with the BibleGet server. Please try again..
    '''</summary>
    Friend Shared ReadOnly Property There_was_a_problem_communicating_with_the_BibleGet_server__Please_try_again_() As String
        Get
            Return ResourceManager.GetString("There was a problem communicating with the BibleGet server. Please try again.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Therefore you will not always be able to use the abbreviations proposed by any single edition of the Bible, you must use the abbreviations that are recognized by the BibleGet engine as listed in the following table:.
    '''</summary>
    Friend Shared ReadOnly Property Therefore_you_will_not_always_be_able_to_use_the_abbreviations_proposed_by_any_single_edition_of_the_Bible__you_must_use_the_abbreviations_that_are_recognized_by_the_BibleGet_engine_as_listed_in_the_following_table_() As String
        Get
            Return ResourceManager.GetString("Therefore you will not always be able to use the abbreviations proposed by any si"& _ 
                    "ngle edition of the Bible, you must use the abbreviations that are recognized by"& _ 
                    " the BibleGet engine as listed in the following table:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This can also be written as &quot;Mt 1&quot;..
    '''</summary>
    Friend Shared ReadOnly Property This_can_also_be_written_as__Mt_1__() As String
        Get
            Return ResourceManager.GetString("This can also be written as ""Mt 1"".", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This can be either the english notation (as explained here: &lt;a href=&quot;https://en.wikipedia.org/wiki/Bible_citation&quot; target=&quot;_blank&quot;&gt;https://en.wikipedia.org/wiki/Bible_citation&lt;/a&gt;), or the european notation as explained here below..
    '''</summary>
    Friend Shared ReadOnly Property This_can_be_either_the_english_notation__as_explained_here__https___en_wikipedia_org_wiki_Bible_citation___or_the_european_notation_as_explained_here_below_() As String
        Get
            Return ResourceManager.GetString("This can be either the english notation (as explained here: https://en.wikipedia."& _ 
                    "org/wiki/Bible_citation), or the european notation as explained here below.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This Help dialog window introduces the user to the usage of the BibleGet I/O plugin for Microsoft Word 2007+..
    '''</summary>
    Friend Shared ReadOnly Property This_Help_dialog_window_introduces_the_user_to_the_usage_of_the_BibleGet_I_O_plugin_for_Microsoft_Word_() As String
        Get
            Return ResourceManager.GetString("This Help dialog window introduces the user to the usage of the BibleGet I/O plug"& _ 
                    "in for Microsoft Word.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This list of versions is updated from the available versions on the BibleGet server, but since the information is stored locally it may be necessary to renew the server information when new versions are added to the BibleGet server database..
    '''</summary>
    Friend Shared ReadOnly Property This_list_of_versions_is_updated_from_the_available_versions_on_the_BibleGet_server__but_since_the_information_is_stored_locally_it_may_be_necessary_to_renew_the_server_information_when_new_versions_are_added_to_the_BibleGet_server_database_() As String
        Get
            Return ResourceManager.GetString("This list of versions is updated from the available versions on the BibleGet serv"& _ 
                    "er, but since the information is stored locally it may be necessary to renew the"& _ 
                    " server information when new versions are added to the BibleGet server database."& _ 
                    "", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This opens a dialog window with some information on the project and it&apos;s plugins, on the author and contributors, and on the current locally stored information about the versions and languages that the BibleGet server supports..
    '''</summary>
    Friend Shared ReadOnly Property This_opens_a_dialog_window_with_some_information_on_the_project_and_it_s_plugins__on_the_author_and_contributors__and_on_the_current_locally_stored_information_about_the_versions_and_languages_that_the_BibleGet_server_supports_() As String
        Get
            Return ResourceManager.GetString("This opens a dialog window with some information on the project and it's plugins,"& _ 
                    " on the author and contributors, and on the current locally stored information a"& _ 
                    "bout the versions and languages that the BibleGet server supports.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This plugin was developed by &lt;b&gt;John R. D&apos;Orazio&lt;/b&gt;, a priest in the diocese of Rome..
    '''</summary>
    Friend Shared ReadOnly Property This_plugin_was_developed_by__b_John_R__D_Orazio__b___a_priest_in_the_diocese_of_Rome_() As String
        Get
            Return ResourceManager.GetString("This plugin was developed by <b>John R. D'Orazio</b>, a priest in the diocese of "& _ 
                    "Rome.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a This will open up your system&apos;s default email application with the bibleget.io@gmail.com feedback address already filled in..
    '''</summary>
    Friend Shared ReadOnly Property This_will_open_up_your_system_s_default_email_application_with_the_bibleget_io_gmail_com_feedback_address_already_filled_in_() As String
        Get
            Return ResourceManager.GetString("This will open up your system's default email application with the bibleget.io@gm"& _ 
                    "ail.com feedback address already filled in.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Type the desired Bible Quote using standard notation:.
    '''</summary>
    Friend Shared ReadOnly Property Type_the_desired_Bible_Quote_using_standard_notation_() As String
        Get
            Return ResourceManager.GetString("Type the desired Bible Quote using standard notation:", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Usage of the Plugin.
    '''</summary>
    Friend Shared ReadOnly Property Usage_of_the_Plugin() As String
        Get
            Return ResourceManager.GetString("Usage of the Plugin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a User Preferences.
    '''</summary>
    Friend Shared ReadOnly Property User_Preferences() As String
        Get
            Return ResourceManager.GetString("User Preferences", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Verse Number.
    '''</summary>
    Friend Shared ReadOnly Property Verse_Number() As String
        Get
            Return ResourceManager.GetString("Verse Number", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Verse Text.
    '''</summary>
    Friend Shared ReadOnly Property Verse_Text() As String
        Get
            Return ResourceManager.GetString("Verse Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Verses (or chapters if applicable) around the dash operator must be consecutive. Instead &lt;{0}&gt; is greater than or equal to &lt;{1}&gt; in the expression &lt;{2}&gt;.
    '''</summary>
    Friend Shared ReadOnly Property Verses__or_chapters_if_applicable__around_the_dash_operator_must_be_consecutive__Instead___0___is_greater_than_or_equal_to___1___in_the_expression___2__() As String
        Get
            Return ResourceManager.GetString("Verses (or chapters if applicable) around the dash operator must be consecutive. "& _ 
                    "Instead <{0}> is greater than or equal to <{1}> in the expression <{2}>", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Verses concatenated by a dot must be consecutive, instead &lt;{0}&gt; is greater than or equal to &lt;{1}&gt; in the expression &lt;{2}&gt; in the query &lt;{3}&gt;.
    '''</summary>
    Friend Shared ReadOnly Property Verses_concatenated_by_a_dot_must_be_consecutive__instead___0___is_greater_than_or_equal_to___1___in_the_expression___2___in_the_query___3__() As String
        Get
            Return ResourceManager.GetString("Verses concatenated by a dot must be consecutive, instead <{0}> is greater than o"& _ 
                    "r equal to <{1}> in the expression <{2}> in the query <{3}>", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a Version.
    '''</summary>
    Friend Shared ReadOnly Property Version() As String
        Get
            Return ResourceManager.GetString("Version", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a When you choose a version or multiple versions to quote from, this choice is automatically saved as a preference, and will be pre-selected the next time you open the &apos;&apos;{0}&apos;&apos; menu item..
    '''</summary>
    Friend Shared ReadOnly Property When_you_choose_a_version_or_multiple_versions_to_quote_from__this_choice_is_automatically_saved_as_a_preference__and_will_be_pre_selected_the_next_time_you_open_the____0____menu_item_() As String
        Get
            Return ResourceManager.GetString("When you choose a version or multiple versions to quote from, this choice is auto"& _ 
                    "matically saved as a preference, and will be pre-selected the next time you open"& _ 
                    " the ''{0}'' menu item.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You cannot have more than one comma and not have a dash!.
    '''</summary>
    Friend Shared ReadOnly Property You_cannot_have_more_than_one_comma_and_not_have_a_dash_() As String
        Get
            Return ResourceManager.GetString("You cannot have more than one comma and not have a dash!", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You cannot send an empty query..
    '''</summary>
    Friend Shared ReadOnly Property You_cannot_send_an_empty_query_() As String
        Get
            Return ResourceManager.GetString("You cannot send an empty query.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You cannot use a dot without first using a comma or a dash. A dot is a liason between verses, which are separated from the chapter by a comma..
    '''</summary>
    Friend Shared ReadOnly Property You_cannot_use_a_dot_without_first_using_a_comma_or_a_dash__A_dot_is_a_liason_between_verses__which_are_separated_from_the_chapter_by_a_comma_() As String
        Get
            Return ResourceManager.GetString("You cannot use a dot without first using a comma or a dash. A dot is a liason bet"& _ 
                    "ween verses, which are separated from the chapter by a comma.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You must choose a Bible version from which to search.
    '''</summary>
    Friend Shared ReadOnly Property You_must_choose_a_Bible_version_from_which_to_search() As String
        Get
            Return ResourceManager.GetString("You must choose a Bible version from which to search", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You must have a valid chapter following the book indicator!.
    '''</summary>
    Friend Shared ReadOnly Property You_must_have_a_valid_chapter_following_the_book_indicator_() As String
        Get
            Return ResourceManager.GetString("You must have a valid chapter following the book indicator!", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You must select at least one version in order to make a request..
    '''</summary>
    Friend Shared ReadOnly Property You_must_select_at_least_one_version_in_order_to_make_a_request_() As String
        Get
            Return ResourceManager.GetString("You must select at least one version in order to make a request.", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You must type a term to search for.
    '''</summary>
    Friend Shared ReadOnly Property You_must_type_a_term_to_search_for() As String
        Get
            Return ResourceManager.GetString("You must type a term to search for", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Cerca una stringa localizzata simile a You seem to have a malformed querystring, there should be only one dash..
    '''</summary>
    Friend Shared ReadOnly Property You_seem_to_have_a_malformed_querystring__there_should_be_only_one_dash_() As String
        Get
            Return ResourceManager.GetString("You seem to have a malformed querystring, there should be only one dash.", resourceCulture)
        End Get
    End Property
End Class
